import {
  SatelliteScene,
  SpectralBand,
  AnalysisResult,
  QueryHistoryItem,
  SavedAnalysis,
} from '../types/satellite';

// Reusable spectral band profiles
export const SENTINEL_2_BANDS: SpectralBand[] = [
  {
    id: 'B01',
    name: 'Coastal Aerosol',
    commonName: 'coastal',
    centralWavelengthMicrons: 0.443,
    bandwidthMicrons: 0.02,
    spatialResolutionMeters: 60,
    description: 'Coastal aerosol retrieval, atmospheric correction, and shallow bathymetry.',
    domain: 'Visible',
  },
  {
    id: 'B02',
    name: 'Blue',
    commonName: 'blue',
    centralWavelengthMicrons: 0.490,
    bandwidthMicrons: 0.065,
    spatialResolutionMeters: 10,
    description: 'Deep water penetration, soil and deciduous vegetation distinction.',
    domain: 'Visible',
  },
  {
    id: 'B03',
    name: 'Green',
    commonName: 'green',
    centralWavelengthMicrons: 0.560,
    bandwidthMicrons: 0.035,
    spatialResolutionMeters: 10,
    description: 'Chlorophyll peak reflectance for vegetation discrimination.',
    domain: 'Visible',
  },
  {
    id: 'B04',
    name: 'Red',
    commonName: 'red',
    centralWavelengthMicrons: 0.665,
    bandwidthMicrons: 0.030,
    spatialResolutionMeters: 10,
    description: 'Chlorophyll absorption band, critical for NDVI and vegetation vigor.',
    domain: 'Visible',
  },
  {
    id: 'B05',
    name: 'Vegetation Red Edge 1',
    commonName: 'rededge1',
    centralWavelengthMicrons: 0.705,
    bandwidthMicrons: 0.015,
    spatialResolutionMeters: 20,
    description: 'Onset of red edge slope, highly sensitive to leaf nitrogen content.',
    domain: 'Red-Edge',
  },
  {
    id: 'B06',
    name: 'Vegetation Red Edge 2',
    commonName: 'rededge2',
    centralWavelengthMicrons: 0.740,
    bandwidthMicrons: 0.015,
    spatialResolutionMeters: 20,
    description: 'Red edge transition zone for leaf area index (LAI) inversion.',
    domain: 'Red-Edge',
  },
  {
    id: 'B07',
    name: 'Vegetation Red Edge 3',
    commonName: 'rededge3',
    centralWavelengthMicrons: 0.783,
    bandwidthMicrons: 0.020,
    spatialResolutionMeters: 20,
    description: 'Upper boundary of red edge plateau.',
    domain: 'Red-Edge',
  },
  {
    id: 'B08',
    name: 'Broad Near-Infrared (NIR)',
    commonName: 'nir',
    centralWavelengthMicrons: 0.842,
    bandwidthMicrons: 0.115,
    spatialResolutionMeters: 10,
    description: 'High reflectance over dense biomass and internal leaf cellular structure.',
    domain: 'Near-Infrared',
  },
  {
    id: 'B8A',
    name: 'Narrow NIR',
    commonName: 'nir08',
    centralWavelengthMicrons: 0.865,
    bandwidthMicrons: 0.020,
    spatialResolutionMeters: 20,
    description: 'Water vapor contamination avoidance band for biophysical estimation.',
    domain: 'Near-Infrared',
  },
  {
    id: 'B11',
    name: 'SWIR 1',
    commonName: 'swir16',
    centralWavelengthMicrons: 1.610,
    bandwidthMicrons: 0.090,
    spatialResolutionMeters: 20,
    description: 'Canopy moisture content, soil vs rock differentiation, snow/cloud separation.',
    domain: 'Shortwave-Infrared',
  },
  {
    id: 'B12',
    name: 'SWIR 2',
    commonName: 'swir22',
    centralWavelengthMicrons: 2.190,
    bandwidthMicrons: 0.180,
    spatialResolutionMeters: 20,
    description: 'Burn scar mapping, mineral exploration, and urban impervious surfaces.',
    domain: 'Shortwave-Infrared',
  },
];

export const LANDSAT_BANDS: SpectralBand[] = [
  {
    id: 'B1',
    name: 'Coastal Aerosol',
    commonName: 'coastal',
    centralWavelengthMicrons: 0.443,
    bandwidthMicrons: 0.016,
    spatialResolutionMeters: 30,
    description: 'Coastal aerosol studies and shallow coastal water evaluation.',
    domain: 'Visible',
  },
  {
    id: 'B2',
    name: 'Blue',
    commonName: 'blue',
    centralWavelengthMicrons: 0.482,
    bandwidthMicrons: 0.060,
    spatialResolutionMeters: 30,
    description: 'Visible blue band for bathymetry and soil composition.',
    domain: 'Visible',
  },
  {
    id: 'B3',
    name: 'Green',
    commonName: 'green',
    centralWavelengthMicrons: 0.562,
    bandwidthMicrons: 0.057,
    spatialResolutionMeters: 30,
    description: 'Visible green band for peak vegetation reflectance.',
    domain: 'Visible',
  },
  {
    id: 'B4',
    name: 'Red',
    commonName: 'red',
    centralWavelengthMicrons: 0.655,
    bandwidthMicrons: 0.037,
    spatialResolutionMeters: 30,
    description: 'Visible red band for chlorophyll absorption differentiation.',
    domain: 'Visible',
  },
  {
    id: 'B5',
    name: 'Near-Infrared',
    commonName: 'nir',
    centralWavelengthMicrons: 0.865,
    bandwidthMicrons: 0.028,
    spatialResolutionMeters: 30,
    description: 'Biomass evaluation and water body delineation.',
    domain: 'Near-Infrared',
  },
  {
    id: 'B6',
    name: 'SWIR 1',
    commonName: 'swir1',
    centralWavelengthMicrons: 1.609,
    bandwidthMicrons: 0.085,
    spatialResolutionMeters: 30,
    description: 'Moisture content in soil and vegetation canopy.',
    domain: 'Shortwave-Infrared',
  },
  {
    id: 'B7',
    name: 'SWIR 2',
    commonName: 'swir2',
    centralWavelengthMicrons: 2.201,
    bandwidthMicrons: 0.187,
    spatialResolutionMeters: 30,
    description: 'Hydrothermal alteration minerals and fire perimeter delineation.',
    domain: 'Shortwave-Infrared',
  },
  {
    id: 'B8',
    name: 'Panchromatic',
    commonName: 'pan',
    centralWavelengthMicrons: 0.590,
    bandwidthMicrons: 0.172,
    spatialResolutionMeters: 15,
    description: 'High-resolution panchromatic band for pan-sharpening.',
    domain: 'Visible',
  },
  {
    id: 'B10',
    name: 'Thermal Infrared 1 (TIRS)',
    commonName: 'tir1',
    centralWavelengthMicrons: 10.9,
    bandwidthMicrons: 0.59,
    spatialResolutionMeters: 100,
    description: 'Surface kinetic temperature and thermal anomaly detection.',
    domain: 'Thermal',
  },
];

export const SAR_BANDS: SpectralBand[] = [
  {
    id: 'VV',
    name: 'C-Band Vertical Transmit / Vertical Receive',
    commonName: 'vv_polarization',
    centralWavelengthMicrons: 55465.0, // 5.54 cm C-band
    bandwidthMicrons: 1000.0,
    spatialResolutionMeters: 20,
    description: 'Sensitive to surface water roughness, open ocean capillary waves, and soil moisture.',
    domain: 'SAR-Microwave',
  },
  {
    id: 'VH',
    name: 'C-Band Vertical Transmit / Horizontal Receive',
    commonName: 'vh_polarization',
    centralWavelengthMicrons: 55465.0,
    bandwidthMicrons: 1000.0,
    spatialResolutionMeters: 20,
    description: 'Cross-polarization volume scattering dominant over forest canopies and crop volume.',
    domain: 'SAR-Microwave',
  },
];

export const PLANETSCOPE_BANDS: SpectralBand[] = [
  {
    id: 'PS-B1',
    name: 'Blue',
    commonName: 'blue',
    centralWavelengthMicrons: 0.485,
    bandwidthMicrons: 0.045,
    spatialResolutionMeters: 3,
    description: 'Sub-3m optical resolution for infrastructure asset inspection.',
    domain: 'Visible',
  },
  {
    id: 'PS-B2',
    name: 'Green',
    commonName: 'green',
    centralWavelengthMicrons: 0.545,
    bandwidthMicrons: 0.050,
    spatialResolutionMeters: 3,
    description: 'High cadence green reflectance band.',
    domain: 'Visible',
  },
  {
    id: 'PS-B3',
    name: 'Red',
    commonName: 'red',
    centralWavelengthMicrons: 0.630,
    bandwidthMicrons: 0.060,
    spatialResolutionMeters: 3,
    description: 'High spatial resolution red band for micro-parcel field boundaries.',
    domain: 'Visible',
  },
  {
    id: 'PS-B4',
    name: 'Near-Infrared',
    commonName: 'nir',
    centralWavelengthMicrons: 0.865,
    bandwidthMicrons: 0.080,
    spatialResolutionMeters: 3,
    description: 'Cadence-optimized near-infrared for rapid crop emergence tracking.',
    domain: 'Near-Infrared',
  },
];

// Curated realistic mock scenes across diverse biomes and sensors
export const MOCK_SCENES: SatelliteScene[] = [
  {
    id: 'S2A_MSIL2A_20240618_ROTTERDAM',
    title: 'Sentinel-2A MSI L2A: Port of Rotterdam & Coastal Maasvlakte',
    mission: 'Sentinel-2',
    sensor: 'Multispectral',
    platformId: 'SENTINEL-2A',
    instrument: 'MSI (MultiSpectral Instrument)',
    acquisitionDate: '2024-06-18T10:45:12Z',
    cloudCoverPercent: 2.1,
    spatialResolutionMeters: 10,
    crs: 'EPSG:32631 (WGS 84 / UTM zone 31N)',
    sunElevationDeg: 61.4,
    sunAzimuthDeg: 158.2,
    processingLevel: 'Level-2A (Bottom of Atmosphere Surface Reflectance)',
    centerCoordinates: { lat: 51.9542, lon: 4.1287 },
    boundingBox: [3.95, 51.85, 4.30, 52.05],
    locationName: 'Port of Rotterdam, Netherlands',
    orbitPass: 'Descending',
    relativeOrbitNumber: 108,
    bands: SENTINEL_2_BANDS,
    simulatedLayerColorMap: {
      true_color: '#1a3c40',
      false_color_ir: '#b83b5e',
      ndvi: '#2dc653',
      sar_amplitude: '#6c757d',
      thermal: '#d97706',
    },
    thumbnailSvgType: 'urban_port',
    stacSelfHref: 'https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2A_MSIL2A_20240618T104512_N0510_R108',
    dataSizeMb: 742.8,
  },
  {
    id: 'S2B_MSIL2A_20240602_AMAZON_PARA',
    title: 'Sentinel-2B MSI L2A: Pará Forest Reserve & River Corridor',
    mission: 'Sentinel-2',
    sensor: 'Multispectral',
    platformId: 'SENTINEL-2B',
    instrument: 'MSI (MultiSpectral Instrument)',
    acquisitionDate: '2024-06-02T13:22:04Z',
    cloudCoverPercent: 6.8,
    spatialResolutionMeters: 10,
    crs: 'EPSG:32721 (WGS 84 / UTM zone 21S)',
    sunElevationDeg: 54.8,
    sunAzimuthDeg: 42.1,
    processingLevel: 'Level-2A (Bottom of Atmosphere Surface Reflectance)',
    centerCoordinates: { lat: -3.4215, lon: -52.1892 },
    boundingBox: [-52.45, -3.65, -51.92, -3.19],
    locationName: 'Amazon Basin (Altamira / Pará), Brazil',
    orbitPass: 'Descending',
    relativeOrbitNumber: 67,
    bands: SENTINEL_2_BANDS,
    simulatedLayerColorMap: {
      true_color: '#164e2e',
      false_color_ir: '#c026d3',
      ndvi: '#10b981',
      sar_amplitude: '#4b5563',
      thermal: '#ea580c',
    },
    thumbnailSvgType: 'rainforest',
    stacSelfHref: 'https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20240602T132204_N0510_R067',
    dataSizeMb: 812.4,
  },
  {
    id: 'LC09_L2SP_20240528_NILE_DELTA',
    title: 'Landsat-9 OLI-2: Nile River Delta & Alexandria Agricultural Margin',
    mission: 'Landsat-8/9',
    sensor: 'Optical',
    platformId: 'LANDSAT-9',
    instrument: 'OLI-2 (Operational Land Imager) / TIRS-2',
    acquisitionDate: '2024-05-28T08:15:40Z',
    cloudCoverPercent: 1.4,
    spatialResolutionMeters: 30,
    crs: 'EPSG:32636 (WGS 84 / UTM zone 36N)',
    sunElevationDeg: 68.2,
    sunAzimuthDeg: 124.7,
    processingLevel: 'Collection 2 Level-2 Surface Reflectance (LaSRC)',
    centerCoordinates: { lat: 31.0254, lon: 30.4782 },
    boundingBox: [30.12, 30.72, 30.84, 31.33],
    locationName: 'Nile Delta, Egypt',
    orbitPass: 'Descending',
    relativeOrbitNumber: 177,
    bands: LANDSAT_BANDS,
    simulatedLayerColorMap: {
      true_color: '#78716c',
      false_color_ir: '#e11d48',
      ndvi: '#84cc16',
      sar_amplitude: '#374151',
      thermal: '#f97316',
    },
    thumbnailSvgType: 'agricultural',
    stacSelfHref: 'https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr/items/LC09_L2SP_177038_20240528_02_T1',
    dataSizeMb: 924.1,
  },
  {
    id: 'S1A_IW_GRDH_20240614_JAKOBSHAVN',
    title: 'Sentinel-1A C-SAR IW: Jakobshavn Isbræ Glacial Calving Front',
    mission: 'Sentinel-1-SAR',
    sensor: 'Synthetic Aperture Radar (SAR)',
    platformId: 'SENTINEL-1A',
    instrument: 'C-SAR (Synthetic Aperture Radar)',
    acquisitionDate: '2024-06-14T20:05:33Z',
    cloudCoverPercent: 0.0, // All-weather microwave
    spatialResolutionMeters: 20,
    crs: 'EPSG:3413 (WGS 84 / NSIDC Sea Ice Polar Stereographic North)',
    sunElevationDeg: 0.0, // Active microwave sensor
    sunAzimuthDeg: 0.0,
    processingLevel: 'GRD-HD (Ground Range Detected High Resolution)',
    centerCoordinates: { lat: 69.1724, lon: -49.8329 },
    boundingBox: [-50.35, 68.95, -49.30, 69.40],
    locationName: 'Jakobshavn Glacier, West Greenland',
    orbitPass: 'Ascending',
    relativeOrbitNumber: 142,
    bands: SAR_BANDS,
    simulatedLayerColorMap: {
      true_color: '#334155',
      false_color_ir: '#3b82f6',
      ndvi: '#475569',
      sar_amplitude: '#e2e8f0',
      thermal: '#0284c7',
    },
    thumbnailSvgType: 'glacial_ice',
    stacSelfHref: 'https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-1-grd/items/S1A_IW_GRDH_1SDV_20240614T200533',
    dataSizeMb: 1140.0,
  },
  {
    id: 'PS_3M_20240610_SF_BAY',
    title: 'PlanetScope SuperDove 3m: San Francisco Bay & Silicon Valley Tech Corridor',
    mission: 'PlanetScope',
    sensor: 'Optical',
    platformId: 'PLANETSCOPE-DOVE-R',
    instrument: 'PlanetScope 8-band SuperDove',
    acquisitionDate: '2024-06-10T18:30:21Z',
    cloudCoverPercent: 4.3,
    spatialResolutionMeters: 3,
    crs: 'EPSG:32610 (WGS 84 / UTM zone 10N)',
    sunElevationDeg: 69.1,
    sunAzimuthDeg: 140.3,
    processingLevel: 'Ortho Scene Surface Reflectance (3B)',
    centerCoordinates: { lat: 37.5841, lon: -122.2543 },
    boundingBox: [-122.48, 37.42, -122.02, 37.75],
    locationName: 'San Francisco Bay Area, California, USA',
    orbitPass: 'Descending',
    relativeOrbitNumber: 31,
    bands: PLANETSCOPE_BANDS,
    simulatedLayerColorMap: {
      true_color: '#0e7490',
      false_color_ir: '#f43f5e',
      ndvi: '#10b981',
      sar_amplitude: '#64748b',
      thermal: '#fb923c',
    },
    thumbnailSvgType: 'bay_valley',
    stacSelfHref: 'https://api.planet.com/data/v1/item-types/PSScene/items/20240610_183021_0e24_3B_AnalyticMS_SR',
    dataSizeMb: 460.5,
  },
  {
    id: 'S2A_MSIL2A_20240611_VALENCIA_ORCHARD',
    title: 'Sentinel-2A MSI L2A: Valencia Coastal Citrus Orchards & Albufera Lagoon',
    mission: 'Sentinel-2',
    sensor: 'Multispectral',
    platformId: 'SENTINEL-2A',
    instrument: 'MSI (MultiSpectral Instrument)',
    acquisitionDate: '2024-06-11T11:00:29Z',
    cloudCoverPercent: 0.8,
    spatialResolutionMeters: 10,
    crs: 'EPSG:32630 (WGS 84 / UTM zone 30N)',
    sunElevationDeg: 67.5,
    sunAzimuthDeg: 151.8,
    processingLevel: 'Level-2A (Bottom of Atmosphere Surface Reflectance)',
    centerCoordinates: { lat: 39.3411, lon: -0.3421 },
    boundingBox: [-0.55, 39.18, -0.15, 39.50],
    locationName: 'Valencia Region, Spain',
    orbitPass: 'Descending',
    relativeOrbitNumber: 51,
    bands: SENTINEL_2_BANDS,
    simulatedLayerColorMap: {
      true_color: '#365314',
      false_color_ir: '#e11d48',
      ndvi: '#22c55e',
      sar_amplitude: '#475569',
      thermal: '#ea580c',
    },
    thumbnailSvgType: 'agricultural',
    stacSelfHref: 'https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2A_MSIL2A_20240611T110029_N0510_R051',
    dataSizeMb: 768.2,
  },
];

export const SAMPLE_QUERIES: string[] = [
  'Assess NDVI vegetation stress in agricultural plots around Valencia',
  'Measure water surface turbidity and vessel congestion in Port of Rotterdam',
  'Quantify forest canopy disturbance in Amazon basin over past 30 days',
  'Detect glacial terminus displacement using Sentinel-1 C-SAR backscatter',
  'Evaluate urban heat surface and impervious cover across San Francisco Bay',
];

export const MOCK_ANALYSIS_RESULTS: Record<string, AnalysisResult> = {
  S2A_MSIL2A_20240618_ROTTERDAM: {
    jobId: 'sim-job-rotterdam-001',
    sceneId: 'S2A_MSIL2A_20240618_ROTTERDAM',
    mission: 'Sentinel-2',
    query: 'Measure water surface turbidity and vessel congestion in Port of Rotterdam',
    timestamp: '2024-06-18T14:32:00Z',
    executiveSummary:
      'SIMULATED ANALYSIS: Coastal water quality indices reveal low total suspended matter in the Maasvlakte deepwater basin. Vessel radar/optical signatures indicate high terminal berth occupancy at 88.4%. No anomalous hydrocarbon surface sheens detected within 10km harbor radius.',
    confidenceScorePercent: 93.8,
    areaAnalyzedSqKm: 342.5,
    keyFindings: [
      'Total Suspended Matter (TSM) index: 4.8 g/m³ (within nominal seasonal baseline).',
      'NDWI (Normalized Difference Water Index) boundary sharp at outer breakwater.',
      'Active commercial container vessel targets identified in fairway: 42 hulls.',
      'Quayside impervious surface reflectance remains stable (+0.4% YoY).',
    ],
    spectralIndices: [
      {
        name: 'NDWI (McFeeters)',
        description: '(Green - NIR) / (Green + NIR) water boundary delineation',
        meanValue: 0.68,
        range: [-0.22, 0.91],
      },
      {
        name: 'SPM / Turbidity Index (Nechad)',
        description: 'Red band reflectance ratio calibrated for suspended particulate matter',
        meanValue: 0.14,
        range: [0.03, 0.42],
      },
      {
        name: 'NDVI (Terrestrial buffer)',
        description: 'Riparian and dune vegetation vigor',
        meanValue: 0.41,
        range: [-0.15, 0.76],
      },
    ],
    metricDeltas: [
      {
        label: 'Mean Water Turbidity',
        value: '4.8 g/m³',
        change: '-8.2%',
        trend: 'decrease',
        baseline: '5.2 g/m³ 5-yr avg',
        unit: 'g/m³',
      },
      {
        label: 'Berth Occupancy',
        value: '88.4%',
        change: '+3.1%',
        trend: 'increase',
        baseline: '85.7% Q2 avg',
        unit: '%',
      },
      {
        label: 'Industrial Thermal Plume Area',
        value: '1.42 km²',
        change: '-0.2%',
        trend: 'stable',
        baseline: '1.43 km²',
        unit: 'km²',
      },
    ],
    anomaliesDetectedCount: 0,
    anomalyNotes: 'No spectral or spatial anomalies exceeded the 3-sigma variance threshold.',
    methodologyCitation: 'Simulated multi-band radiative transfer pipeline (Nechad et al. 2010 TSM / McFeeters 1996 NDWI). Demonstration data only.',
    disclaimer: 'DISCLAIMER: This analysis is simulated for frontend demonstration purposes. Metrics are not scientifically certified and do not represent verified operational intelligence.',
  },
  S2B_MSIL2A_20240602_AMAZON_PARA: {
    jobId: 'sim-job-amazon-002',
    sceneId: 'S2B_MSIL2A_20240602_AMAZON_PARA',
    mission: 'Sentinel-2',
    query: 'Quantify forest canopy disturbance in Amazon basin over past 30 days',
    timestamp: '2024-06-02T16:10:00Z',
    executiveSummary:
      'SIMULATED ANALYSIS: Distinct localized drops in Red-Edge canopy absorption detected along the southwestern logging access corridor. Normalized Burn Ratio (NBR) indicates early-stage clearings totaling ~4.3 km² with elevated soil background exposure.',
    confidenceScorePercent: 91.2,
    areaAnalyzedSqKm: 580.0,
    keyFindings: [
      'Localized canopy gap emergence detected along secondary unpaved trails (sector SW-4).',
      'NDVI dropped from 0.84 to 0.42 across 4.3 km² of cleared primary rain forest.',
      'Shortwave Infrared (SWIR-2 / B12) soil exposure signature elevated by +24%.',
      'Intact primary forest core preserves healthy multi-layered canopy index (>0.82).',
    ],
    spectralIndices: [
      {
        name: 'NDVI (Canopy Vigor)',
        description: '(NIR - Red) / (NIR + Red) vegetation greenness index',
        meanValue: 0.79,
        range: [0.18, 0.92],
      },
      {
        name: 'NBR (Normalized Burn Ratio)',
        description: '(NIR - SWIR2) / (NIR + SWIR2) disturbance sensitivity',
        meanValue: 0.62,
        range: [-0.08, 0.81],
      },
      {
        name: 'NDRE (Red Edge Chlorophyll)',
        description: '(NIR - RedEdge1) / (NIR + RedEdge1) canopy nitrogen proxy',
        meanValue: 0.54,
        range: [0.12, 0.71],
      },
    ],
    metricDeltas: [
      {
        label: 'Disturbed Canopy Footprint',
        value: '4.32 km²',
        change: '+18.5%',
        trend: 'increase',
        baseline: '3.65 km² prior pass',
        unit: 'km²',
      },
      {
        label: 'Mean Core Forest NDVI',
        value: '0.82',
        change: '-0.01',
        trend: 'stable',
        baseline: '0.83 undisturbed',
        unit: 'index',
      },
      {
        label: 'Edge Fragmentation Ratio',
        value: '1.38',
        change: '+6.4%',
        trend: 'increase',
        baseline: '1.30 baseline',
        unit: 'ratio',
      },
    ],
    anomaliesDetectedCount: 3,
    anomalyNotes: 'Cluster of low NBR (< 0.15) pixels detected near coordinates -3.491°, -52.285° indicates recent clearing.',
    methodologyCitation: 'Simulated differential index change detection model (NDVI/NBR thresholding). Demo data only.',
    disclaimer: 'DISCLAIMER: This analysis is simulated for frontend demonstration purposes. Metrics are not scientifically certified and do not represent verified operational intelligence.',
  },
  DEFAULT: {
    jobId: 'sim-job-generic-999',
    sceneId: 'generic',
    mission: 'Sentinel-2',
    query: 'Multi-spectral biophysical surface analysis',
    timestamp: '2024-06-18T12:00:00Z',
    executiveSummary:
      'SIMULATED ANALYSIS: Comprehensive radiometric and index extraction completed for the selected footprint. Spectral response indicates expected seasonal parameters across target land cover classes with clear atmospheric transmittance.',
    confidenceScorePercent: 89.5,
    areaAnalyzedSqKm: 420.0,
    keyFindings: [
      'Radiometric calibration verified within nominal instrument drift limits.',
      'Surface reflectance profiles match regional spectral library baselines.',
      'Cloud masking confirmed cloud-free pixel availability exceeding 94%.',
      'No critical hazard alerts detected within target bounding box.',
    ],
    spectralIndices: [
      {
        name: 'NDVI',
        description: 'Normalized Difference Vegetation Index',
        meanValue: 0.58,
        range: [-0.10, 0.86],
      },
      {
        name: 'NDWI',
        description: 'Normalized Difference Water Index',
        meanValue: -0.21,
        range: [-0.60, 0.72],
      },
    ],
    metricDeltas: [
      {
        label: 'Target Area Coverage',
        value: '420 km²',
        change: '0.0%',
        trend: 'stable',
        baseline: '100% nominal',
        unit: 'km²',
      },
      {
        label: 'Mean Spectral Albedo',
        value: '0.24',
        change: '+1.2%',
        trend: 'stable',
        baseline: '0.23 seasonal',
        unit: 'reflectance',
      },
    ],
    anomaliesDetectedCount: 0,
    anomalyNotes: 'All surface values align with seasonal variance models.',
    methodologyCitation: 'Simulated Level-2A BOA surface reflectance pipeline. Demo data only.',
    disclaimer: 'DISCLAIMER: This analysis is simulated for frontend demonstration purposes. Metrics are not scientifically certified and do not represent verified operational intelligence.',
  },
};

export const INITIAL_QUERY_HISTORY: QueryHistoryItem[] = [
  {
    id: 'hist-001',
    query: 'Measure water surface turbidity and vessel congestion in Port of Rotterdam',
    locationName: 'Port of Rotterdam, Netherlands',
    missionFilter: 'Sentinel-2',
    timestamp: '2024-06-18T09:45:00Z',
    resultCount: 1,
  },
  {
    id: 'hist-002',
    query: 'Quantify forest canopy disturbance in Amazon basin over past 30 days',
    locationName: 'Amazon Basin, Brazil',
    missionFilter: 'Sentinel-2',
    timestamp: '2024-06-17T15:20:00Z',
    resultCount: 1,
  },
  {
    id: 'hist-003',
    query: 'Assess crop NDVI vigor in Nile Delta agricultural corridor',
    locationName: 'Nile Delta, Egypt',
    missionFilter: 'Landsat-8/9',
    timestamp: '2024-06-16T11:10:00Z',
    resultCount: 1,
  },
  {
    id: 'hist-004',
    query: 'Monitor glacial calving front velocities with SAR microwave',
    locationName: 'Jakobshavn Glacier, Greenland',
    missionFilter: 'Sentinel-1-SAR',
    timestamp: '2024-06-15T18:00:00Z',
    resultCount: 1,
  },
];

export const INITIAL_SAVED_ANALYSES: SavedAnalysis[] = [
  {
    id: 'saved-001',
    title: 'Rotterdam Port Harbor Water Quality Baseline',
    query: 'Measure water surface turbidity and vessel congestion in Port of Rotterdam',
    sceneId: 'S2A_MSIL2A_20240618_ROTTERDAM',
    locationName: 'Port of Rotterdam, Netherlands',
    mission: 'Sentinel-2',
    savedAt: '2024-06-18T14:40:00Z',
    tags: ['Maritime', 'Water Quality', 'North Sea'],
    notes: 'Baseline observation prior to dredging operations scheduled for Q3. NDWI index stable at 0.68.',
    keyMetric: 'Turbidity: 4.8 g/m³ (Nominal)',
  },
  {
    id: 'saved-002',
    title: 'Altamira Canopy Clearing Detection Log',
    query: 'Quantify forest canopy disturbance in Amazon basin over past 30 days',
    sceneId: 'S2B_MSIL2A_20240602_AMAZON_PARA',
    locationName: 'Amazon Basin, Brazil',
    mission: 'Sentinel-2',
    savedAt: '2024-06-03T08:12:00Z',
    tags: ['Forestry', 'Deforestation', 'NDVI Alert'],
    notes: 'Logging road expansion detected in sector SW-4. NBR index dropped to 0.18 over 4.3 km².',
    keyMetric: 'Disturbance: 4.32 km² (+18.5%)',
  },
];
